version: "3.8"
services:
  app:
    container_name: chess-api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./:/app"
      - chess_api_data:/app/data
    ports:
      - "1776:1776"

volumes:
  chess_api_data:
    name: chess_api_data
